# Generated by Django 2.2 on 2020-11-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201029_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'категория товаров', 'verbose_name_plural': 'категории товаров'},
        ),
    ]
