# Generated by Django 4.0.5 on 2022-06-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211219_2138'),
        ('mainapp', '0005_auto_20201112_1804'),
    ]

    operations = [
    ]
